---

- name: Install Homebrew packages
  homebrew:
    name: "{{ homebrew_pkgs }}"
    state: present

- name: Install Homebrew Cask packages
  homebrew_cask:
    name: "{{ homebrew_cask_pkgs }}"
    state: upgraded
  ignore_errors: yes