---

- name: install homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_pkgs }}"

- name: install homebrew packages
  homebrew_cask:
  	name: "{{ item }}"
  	state: present
  with_items: "{{ homebrew_cask_pkgs }}"